name: Secrets Test
on: [push]
jobs:
  secrets-test:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      # env:
      #   SUPER_SECRET: ${{ secrets.TEST }}
      run: |
        echo "Secret is set: ${{ secrets.TEST_SECRET }}"