name: Secrets Test
on: [push]
jobs:
  secrets-test:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SuperSecret }}
      run: |
        echo "$SUPER_SECRET"